# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-native-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-native
  template:
    metadata:
      labels:
        app: cloud-native
    spec:
      containers:
      - name: cloud-native
        image: gcr.io/YOUR_PROJECT_ID/cloud-native-app
        ports:
        - containerPort: 3000
