# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cloud-native-service
spec:
  type: LoadBalancer
  selector:
    app: cloud-native
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
